Refactor move duplicated code to reusable methods
samGreenwood2022/EasyRepro pull request #28
Opened 2023-04-20 10:14 UTC by samGreenwood2022

Tidies up the person create code, it had been duplicated a few times, now its 1 re-usable method

2023-04-20 10:44 UTC, ChrisHobbs1992 commented on Microsoft.Dynamics365.UIAutomation.Sample/app.config
Can we find a way to remove person details from the repository for good? Would also be useful to know if there was ever an issue, for example, with test data.

2023-04-20 10:44 UTC, ChrisHobbs1992 commented on PersonSearchDetails/PageObjects/Person/PersonMethods.cs
createBasicPerson should be uppercase - CreateBasicPerson 


Method name & not variable.

2023-04-20 10:45 UTC, ChrisHobbs1992 commented on PersonSearchDetails/PageObjects/Person/PersonMethods.cs
lastname should be camelCase - lastName

2023-04-20 10:51 UTC, ChrisHobbs1992 commented on PersonSearchDetails/PageObjects/Person/PersonMethods.cs
We should refactor out the individual location methods: e.g. 

driver.FindElement(By.XPath("//*[@id=\"firstname\"]/div[1]")).Click();
            driver.FindElement(By.XPath("//*[@id=\"firstname_i\"]")).SendKeys(firstname);
            
            Could be:
            
           IWebElement LocateFirstName(WebDriver driver){
           IWebElement firstNameBox;
           firstNameBox = driver.FindElement(By.XPath("//*[@id=\"firstname\"]/div[1]"));
           return firstNameBox;
           }
           
           We might not have to feed the driver through - would welcome your thoughts on that Sam?
           
           We could consider making this element private too and having:
           
           EnterTextInFirstName(string firstNameText){
           IWebElement firstNameBox;
           firstNameBox = LocateFirstName(driver);
           //Do We have to click into the element before entering text???
           firstNameBox.SendKeys(firstNameText);
           }
           
           ClickFirstName(string firstNameText){
           IWebElement firstNameBox;
           firstNameBox = LocateFirstName(driver);
           firstNameBox.Click();
           }

2023-04-20 10:52 UTC, ChrisHobbs1992 commented on PersonSearchDetails/PageObjects/Person/PersonMethods.cs
xrmBrowser.ThinkTime(1000);

should all be made more robust (e.g. waiting for presence of or lack of presence of any one element - obvious one is save. Wait for the Saved floppy icon, or wait for the loading wheel to no longer be present.

2023-04-20 10:53 UTC, ChrisHobbs1992 commented on PersonSearchDetails/PageObjects/Person/PersonMethods.cs
variable firstname should be camelCase (firstName).

2023-04-20 10:56 UTC, ChrisHobbs1992 commented on PersonSearchDetails/PageObjects/Person/PersonMethods.cs
The fact that CreateBasicPerson returns type string and it is the last name is not very intuitive. We need to comment in why it does this and/or how it is to be used

2023-04-20 11:07 UTC, ChrisHobbs1992 commented on PersonSearchDetails/PageObjects/Person/PersonMethods.cs
We should add the calendar feature for DOB picker into the backlog - do we test this? Do we need to?

2023-04-20 11:08 UTC, ChrisHobbs1992 commented on PersonSearchDetails/PageObjects/Person/PersonMethods.cs
We should add the Lookups from the person create into the backlog too - these will be the standard way to add new values into the fields, so they likely will need to be used in oru tests.

2023-04-20 11:11 UTC, ChrisHobbs1992 commented on PersonSearchDetails/PageObjects/Person/PersonMethods.cs
Frame switching is a bit of a strange one in this product. We need to think about how we will manage it once the code complexity grows and keep an eye on how consistently it works

2023-04-20 11:14 UTC, ChrisHobbs1992 commented on PersonSearchDetails/PageObjects/Person/PersonMethods.cs
In the future for the gender method we could provide a list of valid genders in the reference data in this project.

So it would look like

SelectGender(ReferenceData.Gender.male);

SelectGender(ReferenceData.Gender.female);

SelectGender(ReferenceData.Gender.unknown);

Etc.

2023-04-20 11:15 UTC, ChrisHobbs1992 requested changes
Can we resolve the casing based issues and resubmit this, should be quick fixes. 

Comment against the Create basic person returning the string would also be good, please.

2023-04-20 12:36 UTC, samGreenwood2022 commented on Microsoft.Dynamics365.UIAutomation.Sample/app.config
Person details can be removed permanently from the repository by deleting any branches which contained those details. For example once this branch has been merged into main all other unused branches containing those details can be safely deleted 

If those details exist on someone elses branch and they try to create a PR, the review process will highlight those details and the person who created the PR will have to remove them

2023-04-20 13:25 UTC, samGreenwood2022 commented on PersonSearchDetails/PageObjects/Person/PersonMethods.cs
I've corrected the first 2 issues and ive moved the last point to the backlog for review, we could discuss this in fridays catchup

2023-04-20 13:27 UTC, samGreenwood2022 commented on PersonSearchDetails/PageObjects/Person/PersonMethods.cs
Fixed

2023-04-20 13:29 UTC, samGreenwood2022 commented on PersonSearchDetails/PageObjects/Person/PersonMethods.cs
A more descriptive comment has been added to the code

2023-04-20 13:43 UTC, samGreenwood2022 commented on PersonSearchDetails/PageObjects/Person/PersonMethods.cs
Agreed, i did initially start to use the picker but encountered a few time consuming issues with it so i opted for the easier option, i'll add this task to the backlog though

2023-04-20 13:44 UTC, samGreenwood2022 commented on PersonSearchDetails/PageObjects/Person/PersonMethods.cs
Agreed, more true to real life scenarios, i did start to look at this but after encountering issues i opted to enter the value manually, ive added this to the backlog

2023-04-20 13:45 UTC, samGreenwood2022 commented on PersonSearchDetails/PageObjects/Person/PersonMethods.cs
Added to the backlog

2023-04-20 13:47 UTC, samGreenwood2022 commented on PersonSearchDetails/PageObjects/Person/PersonMethods.cs
Added to the backlog

2023-04-20 13:47 UTC, samGreenwood2022 commented on PersonSearchDetails/PageObjects/Person/PersonMethods.cs
Added to the backlog

2023-04-28 09:32 UTC, ChrisHobbs1992 commented on PersonSearchDetails/StepDefinitions/Person/PersonCreateStepDefinitions.cs
We should also fix firstname, which as a variable should be firstName.

2023-04-28 09:33 UTC, ChrisHobbs1992 approved these changes
firstname should be renamed firstName - but otherwise code checked.

2023-04-28 10:18 UTC, merged